### ISSUE TITLE
Нужна помощь)

### ISSUE THREAD

**Issue by IgorKarpenko-inc** [MaxAlyokhin/transport#1]
Привет Макс. Отличный сайт. Я начинающий программист, тоже из Краснодара. Я решил сделать приложение, которое отслеживает Краснодарские трамваи, но ни как не могу найти API с такой инфой. Может не хватает знаний, может не там ищу. В общем - был бы признателен если бы ты помог с этим. Заранее спасибо)

**Comment by MaxAlyokhin** [comment]
Привет!

API как такового нет, эти данные я нашёл буквально методом тыка. 

Есть сайт: https://www.marsruty.ru/krasnodar/#krasnodar/map
Если зайти в devtools во вкладку Networks, то можно обнаружить, что сайт регулярно опрашивает вот этот URL:
https://www.marsruty.ru/krasnodar/gps.txt

Там строки с текстом, в каждой строке 7 элементов через запятую, которые я интерпретирую так:

1 - тип транспорта
2 - номер маршрута
3 - широта
4 - долгота
5 - скорость
6 - азимут
7 - номер салона

Сам сайт опрашивает сервер примерно раз в 5 секунд, поэтому думаю чаще опрашивать нет смысла.

Ну и надо понимать, что всё это — хак, но никак не нормальный API, и всю эту лавочку могут прикрыть в любой момент, поэтому для серьёзных и, тем более, коммерческих проектов эти данные особо не поюзаешь.

Такие дела.

**Comment by IgorKarpenko-inc** [comment]
Огромное спасибо за ответ. Попробую разобраться с этим) Это не коммерческий проект, так, из интереса для практики) Ещё раз большое спасибо!
